const productsData = {
  newProducts: [
    {
      id: 1,
      name: "Gimbal DJI Ronin S4 Pro Combo",
      image: "../image/Gimbal DJI Ronin S4 Pro Combo (RS4 Pro Combo).jpeg",
      price: 2300000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Balo cho máy ảnh cao cấp",
      image: "../image/Balo cho máy ảnh cao cấp Ulanzi BP09.webp",
      price: 1300000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Canon EOS R50 Kit",
      image: "../image/canon-eos-r50-trang.jpeg",
      price: 17290000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Ngàm Canon EF-RF cho EOS R",
      image: "../image/canon-adapter-ef.jpg",
      price: 1460000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Think Tank Mirrorless Mover 20",
      image: "../image/tui-may-anh-think-tank-mirroeless-mover-20-pewter-1.jpg",
      price: 1200000,
      decrease: 1020000,
      discount: "-15%",
    },
    {
      id: 6,
      name: "Micro RODE Wireless Pro ",
      image: "../image/wireless-pro-1.jpg",
      price: 2100000,
      decrease: 1827000,
      discount: "-13%",
    },
    {
      id: 7,
      name: "Bảo vệ ống kính GoPro Max",
      image: "../image/Picture2-5-402x400.png",
      price: 950000,
      decrease: 760000,
      discount: "-20%",
    },
    {
      id: 8,
      name: "Bộ giá gắn đỡ action camera",
      image: "../image/giado.png",
      price: 1500000,
      decrease: 1350000,
      discount: "-10%",
    },
    {
      id: 9,
      name: "Bộ Vệ Sinh Máy Ảnh Canone",
      image: "../image/110701-bo-ve-sinh-may-anh-canon-400x400.jpg",
      price: 555000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Cover máy ảnh Canon 6",
      image: "../image/152001-vo-cao-su-cover-may-anh-canon-6d-400x400.jpg",
      price: 760000,
    },
    {
      id: 11,
      name: "Lens hood Canon ET",
      image: "../image/172101-lens-hood-canon-et-65b-400x400.jpg",
      price: 999000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Nacro for Sony",
      image: "../image/250501-tube-3-khuc-chup-macro-for-sony-400x400.jpg",
      price: 1240000,
    },
    {
      id: 13,
      name: "Kính lọc Hoya HMC UV",
      image: "../image/1401-kinh-loc-filter-hoya-hmc-uv(c)-400x400.jpg",
      price: 1300000,
    },
    {
      id: 14,
      name: "Sony RM-VPR1 S2",
      image:
        "../image/200901-day-bam-mem-may-anh-for-sony-rm-vpr1-s2-400x400.jpg",
      price: 1700000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Dây Đeo Vai PGYTECH",
      image: "../image/day-deo-vai-pgytech-camera-shoulder-straps.jpg",
      price: 400000,
      decrease: 268000,
      discount: "-33%",
    },
    {
      id: 16,
      name: "SmallRig Tripod BUT2664",
      image: "../image/smallrig-tripod-but2664-di-kem-dau-ball-head.jpg",
      price: 1500000,
      promotion: "new",
    },
    {
      id: 17,
      name: "Yongnuo YN24EX S TTL LED",
      image: "../image/yongnuo-yn24ex-s-ttl-led-macro-flash-for-sony.jpg",
      price: 2130000,
      promotion: "new",
    },
    {
      id: 18,
      name: "Dán màn hình cường lực",
      image: "../image/mieng-dan-cuong-luc-fujifilm.jpg",
      price: 550000,
      promotion: "new",
    },
    {
      id: 19,
      name: "Tube Macro AF Meike MK-F-AF3",
      image: "../image/tube-macro-af-meike-mk-f-af3-for-fujifilm.jpg",
      price: 2200000,
      promotion: "new",
    },
    {
      id: 20,
      name: "Godox Led 36 Video",
      image: "../image/godox-led64-video-.jpg",
      price: 1650000,
      decrease: 1485000,
      discount: "-10%",
    },
    {
      id: 21,
      name: "Raynox DCR-250",
      image: "../image/raynox-dcr-250.jpg",
      price: 890000,
    },
    {
      id: 22,
      name: "Gariz halfcase leather",
      image: "../image/gariz-halfcase-leather-for-nikon-df.jpg",
      price: 1200000,
    },
    {
      id: 23,
      name: "Bao da Canon G16",
      image: "../image/bao-da-canon-g16.jpg",
      price: 870000,
    },
    {
      id: 24,
      name: "Hood Haoge LH-X165 ",
      image:
        "../image/haoge-lens-hood-lh-x165-cho-fujifilm-xf16-55mm-f28-r-lm-wr.jpg",
      price: 3500000,
      decrease: 2333000,
      discount: "-10%",
    },
  ],
  sacMayAnh: [
    {
      id: 1,
      name: "Fujifilm BC-W235",
      image: "../image/fujifilm-bc-w235-500x500.jpg",
      price: 1600000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Fujifilm BC-W126s",
      image: "../image/sac-pin-fujifilm-bc-w126s-500x500.jpg",
      price: 990000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Panasonic AG-VBR50",
      image: "../image/sac-pin-panasonic-ag-vbr50-500x500.jpg",
      price: 950000,
      decrease: 760000,
      discount: "-20%",
    },
    {
      id: 4,
      name: "Ricoh BJ-11",
      image: "../image/sac-ricoh-bj-11-500x500.jpg",
      price: 1200000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Sony AC-VQ1051D",
      image: "../image/sony-ac-vq1051d-500x500.jpg",
      price: 3990000,
      decrease: 3210000,
      discount: "-20%",
    },
    {
      id: 6,
      name: "Nikon MH-25A",
      image: "../image/sac-pin-nikon-mh-25a-500x500.jpg",
      price: 1131000,
    },
    {
      id: 7,
      name: "Sony BC-QZ1",
      image: "../image/sony-bc-qz1-01-500x500.jpg",
      price: 2290000,
    },
    {
      id: 8,
      name: "Nikon MH-25",
      image: "../image/nikon-mh-25-500x500.jpg",
      price: 1250000,
      decrease: 1000000,
      discount: "-20%",
    },
    {
      id: 9,
      name: "Canon LP-E6",
      image: "../image/sac-pin-canon-lp-e6-500x500.jpg",
      price: 1350000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Camelion BC-0905A",
      image: "../image/camelion-bc-0905a-500x500.jpg",
      price: 750000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Canon LP-E12",
      image: "../image/sac-pin-canon-lp-e12-500x500.jpg",
      price: 1600000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Wasabi NP-FZ100 cho Sony",
      image: "../image/wasabi-np-fz100-cho-sony-500x500.jpg",
      price: 579000,
      decrease: 463200,
      discount: "-20%",
    },
    {
      id: 13,
      name: "Li-ion",
      image: "../image/li-ion-danh-cho-sony-fz-100-500x500.jpg",
      price: 2480000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Sony BC-TRV",
      image: "../image/bo-sac-pin-sony-bc-trv-01-500x500.jpg",
      price: 1390000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Canon ACK-E8 AC",
      image: "../image/canon-ack-e8-ac-adapter-kit-500x500.jpg",
      price: 1500000,
      decrease: 1200000,
      discount: "-20%",
    },
    {
      id: 16,
      name: "Panasonic DMW-BTC10",
      image: "../image/sac-pin-panasonic-dmw-btc10-500x500.jpg",
      price: 1420000,
      promotion: "new",
    },
  ],
  chanMayAnh: [
    {
      id: 1,
      name: "Manfrotto 190 Carbon",
      image: "../image/190-carbon-3-section-1.jpg",
      price: 3400000,
      decrease: 2720000,
      discount: "-20%",
    },
    {
      id: 2,
      name: "SmallRig AD-01 3751",
      image: "../image/smallrig-ad-01-3751-1.jpg",
      price: 2550000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Libec LX7M",
      image: "../image/libec-lx7.jpg",
      price: 1300000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Kingjoy VT-1500",
      image: "../image/vt-1500-1.jpg",
      price: 1250000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Kingjoy VT-890H",
      image: "../image/vt-890h-1.jpg",
      price: 850000,
      decrease: 680000,
      discount: "-20%",
    },
    {
      id: 6,
      name: "Kingjoy VT-688",
      image: "../image/vt-688-1.jpg",
      price: 1450000,
      decrease: 1160000,
      discount: "-20%",
    },
    {
      id: 7,
      name: "Ulanzi MT-65",
      image: "../image/mt-65-1.jpg",
      price: 990000,
    },
    {
      id: 8,
      name: "Ulanzi TT31",
      image: "../image/tt31-1.jpg",
      price: 1550000,
    },
    {
      id: 9,
      name: "National Geographic",
      image: "../image/photo-tripod-large-1-1.jpg",
      price: 690000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Leofoto Monopods",
      image: "../image/leofoto-monopods-mp-284c-11-1.jpg",
      price: 1690000,
      promotion: "new",
    },
    {
      id: 11,
      name: "SmallRig Mini BUT2664",
      image: "../image/tabletop-mini-tripod-but2664-1.jpg",
      price: 959000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Leofoto Mr.Y - LY-224C+LH-25R",
      image: "../image/ly-224c-lh-25r-2.jpg",
      price: 2790000,
      decrease: 2310000,
      discount: "-17%",
    },
    {
      id: 13,
      name: "Libec RS-350D",
      image: "../image/libec-lx7.jpg",
      price: 7800000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Joby Gorillapod 3K",
      image: "../image/joby-3k.jpg",
      price: 949000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Gitzo Centrer Ball Head",
      image: "../image/gizto-gt-0545t-3.jpg",
      price: 2500000,
      decrease: 1675000,
      discount: "-33%",
    },
    {
      id: 16,
      name: "Z Plate",
      image: "../image/z-plate.png",
      price: 490000,
      promotion: "new",
    },
  ],
  voMayAnh: [
    {
      id: 1,
      name: "Easy Cover",
      image: "../image/easycover-canon-m50.jpg",
      price: 390000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Silicon case Easy",
      image:
        "../image/bao-silicon-easy-cover-canon-800d-rebel-t7i-kiss-x9i-mau-den-jpg.jpg",
      price: 290000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Silicon case Easy Cover",
      image: "../image/easy-cover-canon-5dmarkiii-5ds-5dsr-1.jpg",
      price: 349000,
      decrease: 279200,
      discount: "-20%",
    },
    {
      id: 4,
      name: "Silicon case Easy Cover",
      image: "../image/bao-silicon-easy-cover-nikon-d5-mau-den-3-jpg.jpg",
      price: 499000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Silicon case Easy Cover ",
      image: "../image/bao5.jpg",
      price: 399000,
      decrease: 370000,
      discount: "-7%",
    },
    {
      id: 6,
      name: "Silicon case Easy Cover",
      image: "../image/bao6.jpg",
      price: 449000,
    },
    {
      id: 7,
      name: "Silicon easyCover camera",
      image: "../image/bao7.jpg",
      price: 399000,
    },
    {
      id: 8,
      name: "Nikon Z5, Z6 Mark II, Z7 Mark",
      image: "../image/bao8.jpg",
      price: 360000,
      decrease: 290000,
      discount: "-18%",
    },
    {
      id: 9,
      name: "Canon R5 / R6",
      image: "../image/bao9.jpg",
      price: 458000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Nikon Z50",
      image: "../image/bao10.jpg",
      price: 220000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Canon 1DX Mark III ",
      image: "../image/bao11.jpg",
      price: 460000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Canon 750D / Rebel T6i",
      image: "../image/bao12.jpg",
      price: 349000,
      decrease: 335000,
      discount: "-4%",
    },
    {
      id: 13,
      name: "Nikon Z9",
      image: "../image/bao13.jpg",
      price: 660000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Fujifilm XT-3",
      image: "../image/bao14.jpg",
      price: 299000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Nikon D810 + battery grip",
      image: "../image/bao15.jpg",
      price: 666000,
      decrease: 579000,
      discount: "-13%",
    },
    {
      id: 16,
      name: "Canon 5D Mark II",
      image: "../image/bao16.jpg",
      price: 888000,
      promotion: "new",
    },
  ],
  boLoc: [
    {
      id: 1,
      name: "Hoya CPL 67mm HD Nano",
      image: "../image/loc1.jpg",
      price: 2650000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Hoya HMC Close Up",
      image: "../image/loc2.jpg",
      price: 450000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Concept A-Series HD Black",
      image: "../image/loc3.jpg",
      price: 555000,
      promotion: "new",
    },
    {
      id: 4,
      name: "B+W F-Pro 022 2X MRC",
      image: "../image/loc4.jpg",
      price: 1000000,
      decrease: 900000,
      discount: "-10%",
    },
    {
      id: 5,
      name: "Meco Variable ND-X",
      image: "../image/loc5.jpg",
      price: 650000,
      decrease: 611000,
      discount: "-6%",
    },
    {
      id: 6,
      name: "Concept Black Mist 1/4",
      image: "../image/loc6.jpg",
      price: 990000,
    },
    {
      id: 7,
      name: "Kase Wolverine",
      image: "../image/loc7.jpg",
      price: 660000,
    },
    {
      id: 8,
      name: "Nikon MH-25",
      image: "../image/nikon-mh-25-500x500.jpg",
      price: 450000,
      decrease: 435000,
      discount: "-2%",
    },
    {
      id: 9,
      name: "BENRO FH100M2 V4",
      image: "../image/loc9.jpg",
      price: 946000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Benro FH100M2 V1",
      image: "../image/loc10.png",
      price: 670000,
      promotion: "new",
    },
    {
      id: 11,
      name: "BENRO FH100 / FH100R95",
      image: "../image/loc11.jpg",
      price: 999999,
      promotion: "new",
    },
    {
      id: 12,
      name: "Hoya 58mm UX II UV",
      image: "../image/loc12.jpg",
      price: 689000,
      decrease: 447000,
      discount: "-6%",
    },
    {
      id: 13,
      name: "Hoya 55mm UX II UV",
      image: "../image/loc13.jpg",
      price: 1000000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Hoya 62mm UX II CPL Slim",
      image: "../image/loc14.jpeg",
      price: 1200000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Hoya 72mm UX II CPL Slim",
      image: "../image/loc15.jpg",
      price: 2500000,
      decrease: 2300000,
      discount: "-8%",
    },
    {
      id: 16,
      name: "XS-Pro Digital ND Vario",
      image: "../image/loc16.jpg",
      price: 2800000,
      promotion: "new",
    },
  ],
  denLed: [
    {
      id: 1,
      name: "Amaran 300c - 300W",
      image: "../image/led1.jpg",
      price: 5000000,
      decrease: 4700000,
      discount: "-6%",
    },
    {
      id: 2,
      name: "Aputure Amaran 60x Bi-Color",
      image: "../image/led2.jpg",
      price: 3400000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Aputure amaran 200x",
      image: "../image/led3.jpg",
      price: 3140000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Nanlite Forza FS200B",
      image: "../image/led4.jpg",
      price: 5200000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Nanlite Forza 200",
      image: "../image/led5.jpg",
      price: 850000,
      decrease: 680000,
      discount: "-20%",
    },
    {
      id: 6,
      name: "Nanlite FS-60B Bi-Color Studio",
      image: "../image/led6.jpg",
      price: 1450000,
      decrease: 1160000,
      discount: "-20%",
    },
    {
      id: 7,
      name: "RX-18TD Falcon Eyes",
      image: "../image/led7.jpg",
      price: 990000,
    },
    {
      id: 8,
      name: "Kit studio 2 đèn Kino 4",
      image: "../image/led8.jpg",
      price: 1550000,
    },
    {
      id: 9,
      name: "K&F 3200K-5500K",
      image: "../image/led9.jpg",
      price: 690000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Nanlite Forza 300",
      image: "../image/led10.jpeg",
      price: 1690000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Led Yongnuo YN600L",
      image: "../image/led11.jpg",
      price: 959000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Ring RL-18",
      image: "../image/led12.jpg",
      price: 2790000,
      decrease: 2310000,
      discount: "-17%",
    },
    {
      id: 13,
      name: " Godox Professional LED",
      image: "../image/led13.jpg",
      price: 7800000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Nanlite Litolite 5C",
      image: "../image/led14.jpg",
      price: 949000,
      promotion: "new",
    },
    {
      id: 15,
      name: "RX-18TD Falcon Eyes",
      image: "../image/led15.jpg",
      price: 2500000,
      decrease: 1675000,
      discount: "-33%",
    },
    {
      id: 16,
      name: "LED DMX",
      image: "../image/led16.jpg",
      price: 490000,
      promotion: "new",
    },
  ],
  tui: [
    {
      id: 1,
      name: "Lowepro Portland 30",
      image: "../image/tui1.webp",
      price: 1600000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Lowepro Hardside CS 60",
      image: "../image/tui2.webp",
      price: 990000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Túi máy quay 504",
      image: "../image/tui3.webp",
      price: 950000,
      decrease: 760000,
      discount: "-20%",
    },
    {
      id: 4,
      name: "Túi máy ảnh 560",
      image: "../image/tui4.webp",
      price: 1200000,
      promotion: "new",
    },
    {
      id: 5,
      name: "Túi máy ảnh 543",
      image: "../image/tui5.webp",
      price: 3990000,
      decrease: 3210000,
      discount: "-20%",
    },
    {
      id: 6,
      name: "Herringbone Timecode Small",
      image: "../image/tui6.webp",
      price: 1131000,
    },
    {
      id: 7,
      name: "Herringbone Maniere Large",
      image: "../image/tui7.webp",
      price: 2290000,
    },
    {
      id: 8,
      name: "Concept Backpack Fits",
      image: "../image/tui8.webp",
      price: 1250000,
      decrease: 1000000,
      discount: "-20%",
    },
    {
      id: 9,
      name: "Túi chuyên dụng 501",
      image: "../image/tui9.webp",
      price: 1350000,
      promotion: "new",
    },
    {
      id: 10,
      name: "Concept Sling Bag",
      image: "../image/tui10.webp",
      price: 750000,
      promotion: "new",
    },
    {
      id: 11,
      name: "Concept Backpack KF13",
      image: "../image/tui11.webp",
      price: 1600000,
      promotion: "new",
    },
    {
      id: 12,
      name: "Lowepro DroneGuard CS300",
      image: "../image/tui12.webp",
      price: 579000,
      decrease: 463200,
      discount: "-20%",
    },
    {
      id: 13,
      name: "Billingham 72 Khaki Canvas",
      image: "../image/tui13.webp",
      price: 2480000,
      promotion: "new",
    },
    {
      id: 14,
      name: "Ba lô Canon",
      image: "../image/tui14.webp",
      price: 1390000,
      promotion: "new",
    },
    {
      id: 15,
      name: "Túi máy ảnh 502",
      image: "../image/tui15.webp",
      price: 1500000,
      decrease: 1200000,
      discount: "-20%",
    },
    {
      id: 16,
      name: "Túi máy ảnh 538",
      image: "../image/tui16.webp",
      price: 1420000,
      promotion: "new",
    },
  ],
};

const productsData2 = {
  newProducts: [
    {
      id: 1,
      name: "Cannon EOS R50 Kit RF-S18",
      image: "/BaiTapLon/image/moi1.webp",
      price: 2550000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Flash Sony HVL-F60RM2",
      image: "/BaiTapLon/image/moi2.jpg",
      price: 2675000,
      promotion: "new",
    },
    {
      id: 3,
      name: "Exascend CF Express",
      image: "/BaiTapLon/image/moi3.jpg",
      price: 1550000,
      promotion: "new",
    },
    {
      id: 4,
      name: "AAA Panasonic Eneloop",
      image: "/BaiTapLon/image/moi4.jpg",
      price: 800000,
      promotion: "new",
    },
  ],
  popularProduct: [
    {
      id: 1,
      name: "Hoya CPL 72mm HD Nano",
      image: "/BaiTapLon/image/best2.jpg",
      price: 4550000,
      promotion: "new",
    },
    {
      id: 2,
      name: "Fujifilm X-T30 Mark II",
      image: "/BaiTapLon/image/best1.webp",
      price: 2600000,
    },
    {
      id: 3,
      name: "Libec LX7",
      image: "/BaiTapLon/image/best3.jpg",
      price: 1600000,
      promotion: "new",
    },
    {
      id: 4,
      name: "Saramonic Blink500",
      image: "/BaiTapLon/image/best4.jpg",
      price: 2350000,
    },
  ],
  discountProduct: [
    {
      id: 1,
      name: "Canon Kingbag Julius",
      image: "/BaiTapLon/image/khuyenmai2.jpg",
      price: 999000,
      decrease: 929000,
      discount: "-7%",
    },
    {
      id: 2,
      name: "Colbor CL220R RGB",
      image: "/BaiTapLon/image/khuyenmai3.jpg",
      price: 2450000,
      decrease: 1911000,
      discount: "-22%",
    },
    {
      id: 3,
      name: "Hood ES-65B",
      image: "/BaiTapLon/image/khuyenmai4.jpg",
      price: 700000,
      decrease: 420000,
      discount: "-40%",
    },
    {
      id: 4,
      name: "Cannon EOS 250D Kit EF-S18",
      image: "/BaiTapLon/image/khuyenmai1.webp",
      price: 1300000,
      decrease: 1105000,
      discount: "-15%",
    },
  ],
};
